# Bắt đầu từ image Node.js chính thức
FROM node:22

# Thiết lập thư mục làm việc trong container
WORKDIR /app

# Sao chép file package.json và cài đặt các dependencies
COPY package*.json ./
RUN npm install

# Sao chép toàn bộ mã nguồn vào container
COPY . .

# Mở cổng để ứng dụng có thể truy cập từ bên ngoài
EXPOSE 3000

# Chạy ứng dụng
CMD ["npm", "start"]
